var searchData=
[
  ['saliency',['Saliency',['../d9/dcd/classcv_1_1saliency_1_1Saliency.html',1,'cv::saliency']]],
  ['satcasthelper',['SatCastHelper',['../dc/db0/structcv_1_1cudev_1_1vec__math__detail_1_1SatCastHelper.html',1,'cv::cudev::vec_math_detail']]],
  ['satcasthelper_3c_201_2c_20vecd_20_3e',['SatCastHelper&lt; 1, VecD &gt;',['../d2/d31/structcv_1_1cudev_1_1vec__math__detail_1_1SatCastHelper_3_011_00_01VecD_01_4.html',1,'cv::cudev::vec_math_detail']]],
  ['satcasthelper_3c_202_2c_20vecd_20_3e',['SatCastHelper&lt; 2, VecD &gt;',['../dc/dbc/structcv_1_1cudev_1_1vec__math__detail_1_1SatCastHelper_3_012_00_01VecD_01_4.html',1,'cv::cudev::vec_math_detail']]],
  ['satcasthelper_3c_203_2c_20vecd_20_3e',['SatCastHelper&lt; 3, VecD &gt;',['../d8/dbe/structcv_1_1cudev_1_1vec__math__detail_1_1SatCastHelper_3_013_00_01VecD_01_4.html',1,'cv::cudev::vec_math_detail']]],
  ['satcasthelper_3c_204_2c_20vecd_20_3e',['SatCastHelper&lt; 4, VecD &gt;',['../df/d18/structcv_1_1cudev_1_1vec__math__detail_1_1SatCastHelper_3_014_00_01VecD_01_4.html',1,'cv::cudev::vec_math_detail']]],
  ['saturate_5fcast_5ffp16_5ffunc',['saturate_cast_fp16_func',['../de/d9b/structcv_1_1cudev_1_1saturate__cast__fp16__func.html',1,'cv::cudev']]],
  ['saturate_5fcast_5ffp16_5ffunc_3c_20float_2c_20short_20_3e',['saturate_cast_fp16_func&lt; float, short &gt;',['../d3/d11/structcv_1_1cudev_1_1saturate__cast__fp16__func_3_01float_00_01short_01_4.html',1,'cv::cudev']]],
  ['saturate_5fcast_5ffp16_5ffunc_3c_20short_2c_20float_20_3e',['saturate_cast_fp16_func&lt; short, float &gt;',['../dc/dc5/structcv_1_1cudev_1_1saturate__cast__fp16__func_3_01short_00_01float_01_4.html',1,'cv::cudev']]],
  ['saturate_5fcast_5ffunc',['saturate_cast_func',['../dc/d99/structcv_1_1cudev_1_1saturate__cast__func.html',1,'cv::cudev']]],
  ['savedindexparams',['SavedIndexParams',['../de/de8/structcv_1_1flann_1_1SavedIndexParams.html',1,'cv::flann']]],
  ['savedindexparams',['SavedIndexParams',['../dc/d2a/structcvflann_1_1SavedIndexParams.html',1,'cvflann']]],
  ['scalar',['Scalar',['../d8/d72/classcv_1_1gapi_1_1own_1_1Scalar.html',1,'cv::gapi::own']]],
  ['scalar_5f',['Scalar_',['../d1/da0/classcv_1_1Scalar__.html',1,'cv']]],
  ['scalar_5f_3c_20double_20_3e',['Scalar_&lt; double &gt;',['../d1/da0/classcv_1_1Scalar__.html',1,'cv']]],
  ['scalar_5fwrapper',['scalar_wrapper',['../d2/d64/structcv_1_1detail_1_1scalar__wrapper.html',1,'cv::detail']]],
  ['scalar_5fwrapper_5fgpu',['scalar_wrapper_gpu',['../df/db3/structcv_1_1detail_1_1scalar__wrapper__gpu.html',1,'cv::detail']]],
  ['scalelayer',['ScaleLayer',['../dd/dde/classcv_1_1dnn_1_1ScaleLayer.html',1,'cv::dnn']]],
  ['scharrxptr',['ScharrXPtr',['../d7/d71/structcv_1_1cudev_1_1ScharrXPtr.html',1,'cv::cudev']]],
  ['scharrxptrsz',['ScharrXPtrSz',['../d2/d88/structcv_1_1cudev_1_1ScharrXPtrSz.html',1,'cv::cudev']]],
  ['scharryptr',['ScharrYPtr',['../d0/d70/structcv_1_1cudev_1_1ScharrYPtr.html',1,'cv::cudev']]],
  ['scharryptrsz',['ScharrYPtrSz',['../dd/def/structcv_1_1cudev_1_1ScharrYPtrSz.html',1,'cv::cudev']]],
  ['scratch_5fhelper',['scratch_helper',['../db/df4/structcv_1_1detail_1_1scratch__helper.html',1,'cv::detail']]],
  ['scratch_5fhelper_3c_20false_2c_20impl_2c_20ins_2e_2e_2e_20_3e',['scratch_helper&lt; false, Impl, Ins... &gt;',['../d0/d94/structcv_1_1detail_1_1scratch__helper_3_01false_00_01Impl_00_01Ins_8_8_8_01_4.html',1,'cv::detail']]],
  ['scratch_5fhelper_3c_20true_2c_20impl_2c_20ins_2e_2e_2e_20_3e',['scratch_helper&lt; true, Impl, Ins... &gt;',['../dd/d8e/structcv_1_1detail_1_1scratch__helper_3_01true_00_01Impl_00_01Ins_8_8_8_01_4.html',1,'cv::detail']]],
  ['seamfinder',['SeamFinder',['../d7/d09/classcv_1_1detail_1_1SeamFinder.html',1,'cv::detail']]],
  ['searchparams',['SearchParams',['../d5/d03/structcv_1_1flann_1_1SearchParams.html',1,'cv::flann']]],
  ['searchparams',['SearchParams',['../d6/d59/structcvflann_1_1SearchParams.html',1,'cvflann']]],
  ['segmentationparameters',['SegmentationParameters',['../d9/dbf/structcv_1_1bioinspired_1_1SegmentationParameters.html',1,'cv::bioinspired']]],
  ['selectif',['SelectIf',['../d8/d1b/structcv_1_1cudev_1_1SelectIf.html',1,'cv::cudev']]],
  ['selectif_3c_20false_2c_20thentype_2c_20elsetype_20_3e',['SelectIf&lt; false, ThenType, ElseType &gt;',['../dd/da7/structcv_1_1cudev_1_1SelectIf_3_01false_00_01ThenType_00_01ElseType_01_4.html',1,'cv::cudev']]],
  ['selectivesearchsegmentation',['SelectiveSearchSegmentation',['../d6/d6d/classcv_1_1ximgproc_1_1segmentation_1_1SelectiveSearchSegmentation.html',1,'cv::ximgproc::segmentation']]],
  ['selectivesearchsegmentationstrategy',['SelectiveSearchSegmentationStrategy',['../dc/d7a/classcv_1_1ximgproc_1_1segmentation_1_1SelectiveSearchSegmentationStrategy.html',1,'cv::ximgproc::segmentation']]],
  ['selectivesearchsegmentationstrategycolor',['SelectiveSearchSegmentationStrategyColor',['../de/dab/classcv_1_1ximgproc_1_1segmentation_1_1SelectiveSearchSegmentationStrategyColor.html',1,'cv::ximgproc::segmentation']]],
  ['selectivesearchsegmentationstrategyfill',['SelectiveSearchSegmentationStrategyFill',['../d9/db3/classcv_1_1ximgproc_1_1segmentation_1_1SelectiveSearchSegmentationStrategyFill.html',1,'cv::ximgproc::segmentation']]],
  ['selectivesearchsegmentationstrategymultiple',['SelectiveSearchSegmentationStrategyMultiple',['../d8/d8e/classcv_1_1ximgproc_1_1segmentation_1_1SelectiveSearchSegmentationStrategyMultiple.html',1,'cv::ximgproc::segmentation']]],
  ['selectivesearchsegmentationstrategysize',['SelectiveSearchSegmentationStrategySize',['../d0/d10/classcv_1_1ximgproc_1_1segmentation_1_1SelectiveSearchSegmentationStrategySize.html',1,'cv::ximgproc::segmentation']]],
  ['selectivesearchsegmentationstrategytexture',['SelectiveSearchSegmentationStrategyTexture',['../d6/d17/classcv_1_1ximgproc_1_1segmentation_1_1SelectiveSearchSegmentationStrategyTexture.html',1,'cv::ximgproc::segmentation']]],
  ['sfmlibmveuclideanreconstruction',['SFMLibmvEuclideanReconstruction',['../de/d42/classcv_1_1sfm_1_1SFMLibmvEuclideanReconstruction.html',1,'cv::sfm']]],
  ['shapecontextdistanceextractor',['ShapeContextDistanceExtractor',['../d8/de3/classcv_1_1ShapeContextDistanceExtractor.html',1,'cv']]],
  ['shapedistanceextractor',['ShapeDistanceExtractor',['../dc/dbf/classcv_1_1ShapeDistanceExtractor.html',1,'cv']]],
  ['shapetransformer',['ShapeTransformer',['../df/dfe/classcv_1_1ShapeTransformer.html',1,'cv']]],
  ['shared_5flock_5fguard',['shared_lock_guard',['../d9/d7f/classcv_1_1utils_1_1shared__lock__guard.html',1,'cv::utils']]],
  ['shiftlayer',['ShiftLayer',['../d3/dd8/classcv_1_1dnn_1_1ShiftLayer.html',1,'cv::dnn']]],
  ['shufflechannellayer',['ShuffleChannelLayer',['../de/d24/classcv_1_1dnn_1_1ShuffleChannelLayer.html',1,'cv::dnn']]],
  ['sift',['SIFT',['../d5/d3c/classcv_1_1xfeatures2d_1_1SIFT.html',1,'cv::xfeatures2d']]],
  ['sigmoidlayer',['SigmoidLayer',['../dc/d09/classcv_1_1dnn_1_1SigmoidLayer.html',1,'cv::dnn']]],
  ['similarrects',['SimilarRects',['../d1/d65/classcv_1_1SimilarRects.html',1,'cv']]],
  ['simpleblobdetector',['SimpleBlobDetector',['../d0/d7a/classcv_1_1SimpleBlobDetector.html',1,'cv']]],
  ['simpledistance',['simpleDistance',['../d9/d12/structcvflann_1_1simpleDistance.html',1,'cvflann']]],
  ['simpledistance_3c_20chisquaredistance_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['simpleDistance&lt; ChiSquareDistance&lt; ElementType &gt;, ElementType &gt;',['../dd/d95/structcvflann_1_1simpleDistance_3_01ChiSquareDistance_3_01ElementType_01_4_00_01ElementType_01_4.html',1,'cvflann']]],
  ['simpledistance_3c_20hellingerdistance_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['simpleDistance&lt; HellingerDistance&lt; ElementType &gt;, ElementType &gt;',['../db/d88/structcvflann_1_1simpleDistance_3_01HellingerDistance_3_01ElementType_01_4_00_01ElementType_01_4.html',1,'cvflann']]],
  ['simpledistance_3c_20l2_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['simpleDistance&lt; L2&lt; ElementType &gt;, ElementType &gt;',['../dc/d3c/structcvflann_1_1simpleDistance_3_01L2_3_01ElementType_01_4_00_01ElementType_01_4.html',1,'cvflann']]],
  ['simpledistance_3c_20l2_5fsimple_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['simpleDistance&lt; L2_Simple&lt; ElementType &gt;, ElementType &gt;',['../d5/da0/structcvflann_1_1simpleDistance_3_01L2__Simple_3_01ElementType_01_4_00_01ElementType_01_4.html',1,'cvflann']]],
  ['simpledistance_3c_20minkowskidistance_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['simpleDistance&lt; MinkowskiDistance&lt; ElementType &gt;, ElementType &gt;',['../db/dd1/structcvflann_1_1simpleDistance_3_01MinkowskiDistance_3_01ElementType_01_4_00_01ElementType_01_4.html',1,'cvflann']]],
  ['simplewb',['SimpleWB',['../d1/d8b/classcv_1_1xphoto_1_1SimpleWB.html',1,'cv::xphoto']]],
  ['simulatedannealingsolversystem',['SimulatedAnnealingSolverSystem',['../dc/db4/structcv_1_1ml_1_1SimulatedAnnealingSolverSystem.html',1,'cv::ml']]],
  ['sin_5ffunc',['sin_func',['../d1/d05/structcv_1_1cudev_1_1sin__func.html',1,'cv::cudev']]],
  ['sin_5ffunc_3c_20double_20_3e',['sin_func&lt; double &gt;',['../d8/d1c/structcv_1_1cudev_1_1sin__func_3_01double_01_4.html',1,'cv::cudev']]],
  ['sin_5ffunc_3c_20float_20_3e',['sin_func&lt; float &gt;',['../d6/d2b/structcv_1_1cudev_1_1sin__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['sin_5ffunc_3c_20schar_20_3e',['sin_func&lt; schar &gt;',['../d8/d1b/structcv_1_1cudev_1_1sin__func_3_01schar_01_4.html',1,'cv::cudev']]],
  ['sin_5ffunc_3c_20short_20_3e',['sin_func&lt; short &gt;',['../dd/d6f/structcv_1_1cudev_1_1sin__func_3_01short_01_4.html',1,'cv::cudev']]],
  ['sin_5ffunc_3c_20uchar_20_3e',['sin_func&lt; uchar &gt;',['../d2/dfd/structcv_1_1cudev_1_1sin__func_3_01uchar_01_4.html',1,'cv::cudev']]],
  ['sin_5ffunc_3c_20uint_20_3e',['sin_func&lt; uint &gt;',['../d5/dbd/structcv_1_1cudev_1_1sin__func_3_01uint_01_4.html',1,'cv::cudev']]],
  ['sin_5ffunc_3c_20ushort_20_3e',['sin_func&lt; ushort &gt;',['../d8/d22/structcv_1_1cudev_1_1sin__func_3_01ushort_01_4.html',1,'cv::cudev']]],
  ['singlemaskchannels',['SingleMaskChannels',['../db/dce/structcv_1_1cudev_1_1SingleMaskChannels.html',1,'cv::cudev']]],
  ['singlemaskchannelssz',['SingleMaskChannelsSz',['../d0/d19/structcv_1_1cudev_1_1SingleMaskChannelsSz.html',1,'cv::cudev']]],
  ['singlepolicy',['SinglePolicy',['../de/d31/classcvflann_1_1anyimpl_1_1SinglePolicy.html',1,'cvflann::anyimpl']]],
  ['sinh_5ffunc',['sinh_func',['../d8/da0/structcv_1_1cudev_1_1sinh__func.html',1,'cv::cudev']]],
  ['sinh_5ffunc_3c_20double_20_3e',['sinh_func&lt; double &gt;',['../db/dde/structcv_1_1cudev_1_1sinh__func_3_01double_01_4.html',1,'cv::cudev']]],
  ['sinh_5ffunc_3c_20float_20_3e',['sinh_func&lt; float &gt;',['../d3/df1/structcv_1_1cudev_1_1sinh__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['sinh_5ffunc_3c_20schar_20_3e',['sinh_func&lt; schar &gt;',['../de/df6/structcv_1_1cudev_1_1sinh__func_3_01schar_01_4.html',1,'cv::cudev']]],
  ['sinh_5ffunc_3c_20short_20_3e',['sinh_func&lt; short &gt;',['../da/d3e/structcv_1_1cudev_1_1sinh__func_3_01short_01_4.html',1,'cv::cudev']]],
  ['sinh_5ffunc_3c_20uchar_20_3e',['sinh_func&lt; uchar &gt;',['../d4/dd2/structcv_1_1cudev_1_1sinh__func_3_01uchar_01_4.html',1,'cv::cudev']]],
  ['sinh_5ffunc_3c_20uint_20_3e',['sinh_func&lt; uint &gt;',['../de/d13/structcv_1_1cudev_1_1sinh__func_3_01uint_01_4.html',1,'cv::cudev']]],
  ['sinh_5ffunc_3c_20ushort_20_3e',['sinh_func&lt; ushort &gt;',['../d9/d38/structcv_1_1cudev_1_1sinh__func_3_01ushort_01_4.html',1,'cv::cudev']]],
  ['sinusoidalpattern',['SinusoidalPattern',['../d6/d96/classcv_1_1structured__light_1_1SinusoidalPattern.html',1,'cv::structured_light']]],
  ['size',['Size',['../d7/d3e/classcv_1_1gapi_1_1own_1_1Size.html',1,'cv::gapi::own']]],
  ['size_5f',['Size_',['../d6/d50/classcv_1_1Size__.html',1,'cv']]],
  ['size_5f_3c_20float_20_3e',['Size_&lt; float &gt;',['../d6/d50/classcv_1_1Size__.html',1,'cv']]],
  ['skeleton',['skeleton',['../d4/d66/structcv_1_1datasets_1_1skeleton.html',1,'cv::datasets']]],
  ['sl2',['SL2',['../d5/d46/structcv_1_1SL2.html',1,'cv']]],
  ['slam_5fkitti',['SLAM_kitti',['../d6/d92/classcv_1_1datasets_1_1SLAM__kitti.html',1,'cv::datasets']]],
  ['slam_5fkittiobj',['SLAM_kittiObj',['../da/df4/structcv_1_1datasets_1_1SLAM__kittiObj.html',1,'cv::datasets']]],
  ['slam_5ftumindoor',['SLAM_tumindoor',['../da/d91/classcv_1_1datasets_1_1SLAM__tumindoor.html',1,'cv::datasets']]],
  ['slam_5ftumindoorobj',['SLAM_tumindoorObj',['../d7/d56/structcv_1_1datasets_1_1SLAM__tumindoorObj.html',1,'cv::datasets']]],
  ['slicelayer',['SliceLayer',['../de/d61/classcv_1_1dnn_1_1SliceLayer.html',1,'cv::dnn']]],
  ['sobelxptr',['SobelXPtr',['../de/dc8/structcv_1_1cudev_1_1SobelXPtr.html',1,'cv::cudev']]],
  ['sobelxptrsz',['SobelXPtrSz',['../d7/d84/structcv_1_1cudev_1_1SobelXPtrSz.html',1,'cv::cudev']]],
  ['sobelyptr',['SobelYPtr',['../d0/da6/structcv_1_1cudev_1_1SobelYPtr.html',1,'cv::cudev']]],
  ['sobelyptrsz',['SobelYPtrSz',['../dd/dc6/structcv_1_1cudev_1_1SobelYPtrSz.html',1,'cv::cudev']]],
  ['softdouble',['softdouble',['../de/df1/structcv_1_1softdouble.html',1,'cv']]],
  ['softfloat',['softfloat',['../d7/d2f/structcv_1_1softfloat.html',1,'cv']]],
  ['softmaxlayer',['SoftmaxLayer',['../d8/d18/classcv_1_1dnn_1_1SoftmaxLayer.html',1,'cv::dnn']]],
  ['sparsemat',['SparseMat',['../dd/da9/classcv_1_1SparseMat.html',1,'cv']]],
  ['sparsemat_5f',['SparseMat_',['../d7/d8a/classcv_1_1SparseMat__.html',1,'cv']]],
  ['sparsematchinterpolator',['SparseMatchInterpolator',['../d4/da8/classcv_1_1ximgproc_1_1SparseMatchInterpolator.html',1,'cv::ximgproc']]],
  ['sparsematconstiterator',['SparseMatConstIterator',['../df/dec/classcv_1_1SparseMatConstIterator.html',1,'cv']]],
  ['sparsematconstiterator_5f',['SparseMatConstIterator_',['../d9/d29/classcv_1_1SparseMatConstIterator__.html',1,'cv']]],
  ['sparsematiterator',['SparseMatIterator',['../d5/d9b/classcv_1_1SparseMatIterator.html',1,'cv']]],
  ['sparsematiterator_5f',['SparseMatIterator_',['../d3/d24/classcv_1_1SparseMatIterator__.html',1,'cv']]],
  ['sparseopticalflow',['SparseOpticalFlow',['../de/d14/classcv_1_1SparseOpticalFlow.html',1,'cv']]],
  ['sparseopticalflow',['SparseOpticalFlow',['../d5/dcf/classcv_1_1cuda_1_1SparseOpticalFlow.html',1,'cv::cuda']]],
  ['sparsepyrlkoptflowestimator',['SparsePyrLkOptFlowEstimator',['../d1/d4b/classcv_1_1videostab_1_1SparsePyrLkOptFlowEstimator.html',1,'cv::videostab']]],
  ['sparsepyrlkopticalflow',['SparsePyrLKOpticalFlow',['../d7/d08/classcv_1_1SparsePyrLKOpticalFlow.html',1,'cv']]],
  ['sparsepyrlkopticalflow',['SparsePyrLKOpticalFlow',['../d7/d05/classcv_1_1cuda_1_1SparsePyrLKOpticalFlow.html',1,'cv::cuda']]],
  ['sphericalportraitprojector',['SphericalPortraitProjector',['../d3/d0d/structcv_1_1detail_1_1SphericalPortraitProjector.html',1,'cv::detail']]],
  ['sphericalportraitwarper',['SphericalPortraitWarper',['../d8/d70/classcv_1_1detail_1_1SphericalPortraitWarper.html',1,'cv::detail']]],
  ['sphericalprojector',['SphericalProjector',['../d0/d88/structcv_1_1detail_1_1SphericalProjector.html',1,'cv::detail']]],
  ['sphericalwarper',['SphericalWarper',['../d3/d3c/classcv_1_1SphericalWarper.html',1,'cv']]],
  ['sphericalwarper',['SphericalWarper',['../d6/dd0/classcv_1_1detail_1_1SphericalWarper.html',1,'cv::detail']]],
  ['sphericalwarpergpu',['SphericalWarperGpu',['../db/d09/classcv_1_1detail_1_1SphericalWarperGpu.html',1,'cv::detail']]],
  ['split',['Split',['../d9/d37/classcv_1_1ml_1_1DTrees_1_1Split.html',1,'cv::ml::DTrees']]],
  ['splitlayer',['SplitLayer',['../dd/df9/classcv_1_1dnn_1_1SplitLayer.html',1,'cv::dnn']]],
  ['sqr_5ffunc',['sqr_func',['../d9/d1d/structcv_1_1cudev_1_1sqr__func.html',1,'cv::cudev']]],
  ['sqrt_5ffunc',['sqrt_func',['../d9/d47/structcv_1_1cudev_1_1sqrt__func.html',1,'cv::cudev']]],
  ['sqrt_5ffunc_3c_20double_20_3e',['sqrt_func&lt; double &gt;',['../d4/d9d/structcv_1_1cudev_1_1sqrt__func_3_01double_01_4.html',1,'cv::cudev']]],
  ['sqrt_5ffunc_3c_20float_20_3e',['sqrt_func&lt; float &gt;',['../d8/dd2/structcv_1_1cudev_1_1sqrt__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['sqrt_5ffunc_3c_20schar_20_3e',['sqrt_func&lt; schar &gt;',['../da/d64/structcv_1_1cudev_1_1sqrt__func_3_01schar_01_4.html',1,'cv::cudev']]],
  ['sqrt_5ffunc_3c_20short_20_3e',['sqrt_func&lt; short &gt;',['../d2/d6a/structcv_1_1cudev_1_1sqrt__func_3_01short_01_4.html',1,'cv::cudev']]],
  ['sqrt_5ffunc_3c_20uchar_20_3e',['sqrt_func&lt; uchar &gt;',['../d9/d33/structcv_1_1cudev_1_1sqrt__func_3_01uchar_01_4.html',1,'cv::cudev']]],
  ['sqrt_5ffunc_3c_20uint_20_3e',['sqrt_func&lt; uint &gt;',['../d0/d7b/structcv_1_1cudev_1_1sqrt__func_3_01uint_01_4.html',1,'cv::cudev']]],
  ['sqrt_5ffunc_3c_20ushort_20_3e',['sqrt_func&lt; ushort &gt;',['../df/df4/structcv_1_1cudev_1_1sqrt__func_3_01ushort_01_4.html',1,'cv::cudev']]],
  ['squaredistance',['squareDistance',['../dc/d68/structcvflann_1_1squareDistance.html',1,'cvflann']]],
  ['squaredistance_3c_20chisquaredistance_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['squareDistance&lt; ChiSquareDistance&lt; ElementType &gt;, ElementType &gt;',['../d2/deb/structcvflann_1_1squareDistance_3_01ChiSquareDistance_3_01ElementType_01_4_00_01ElementType_01_4.html',1,'cvflann']]],
  ['squaredistance_3c_20hellingerdistance_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['squareDistance&lt; HellingerDistance&lt; ElementType &gt;, ElementType &gt;',['../dc/d3f/structcvflann_1_1squareDistance_3_01HellingerDistance_3_01ElementType_01_4_00_01ElementType_01_4.html',1,'cvflann']]],
  ['squaredistance_3c_20l2_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['squareDistance&lt; L2&lt; ElementType &gt;, ElementType &gt;',['../d8/db8/structcvflann_1_1squareDistance_3_01L2_3_01ElementType_01_4_00_01ElementType_01_4.html',1,'cvflann']]],
  ['squaredistance_3c_20l2_5fsimple_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['squareDistance&lt; L2_Simple&lt; ElementType &gt;, ElementType &gt;',['../d3/d86/structcvflann_1_1squareDistance_3_01L2__Simple_3_01ElementType_01_4_00_01ElementType_01_4.html',1,'cvflann']]],
  ['squaredistance_3c_20minkowskidistance_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['squareDistance&lt; MinkowskiDistance&lt; ElementType &gt;, ElementType &gt;',['../dc/d73/structcvflann_1_1squareDistance_3_01MinkowskiDistance_3_01ElementType_01_4_00_01ElementType_01_4.html',1,'cvflann']]],
  ['stabilizerbase',['StabilizerBase',['../d2/d6c/classcv_1_1videostab_1_1StabilizerBase.html',1,'cv::videostab']]],
  ['standardcollector',['StandardCollector',['../d4/d8d/classcv_1_1face_1_1StandardCollector.html',1,'cv::face']]],
  ['stardetector',['StarDetector',['../dd/d39/classcv_1_1xfeatures2d_1_1StarDetector.html',1,'cv::xfeatures2d']]],
  ['starkernelcensus',['StarKernelCensus',['../db/d3b/classcv_1_1stereo_1_1StarKernelCensus.html',1,'cv::stereo']]],
  ['startstoptimer',['StartStopTimer',['../de/dd0/classcvflann_1_1StartStopTimer.html',1,'cvflann']]],
  ['staticsaliency',['StaticSaliency',['../d5/d87/classcv_1_1saliency_1_1StaticSaliency.html',1,'cv::saliency']]],
  ['staticsaliencyfinegrained',['StaticSaliencyFineGrained',['../da/dd0/classcv_1_1saliency_1_1StaticSaliencyFineGrained.html',1,'cv::saliency']]],
  ['staticsaliencyspectralresidual',['StaticSaliencySpectralResidual',['../df/d37/classcv_1_1saliency_1_1StaticSaliencySpectralResidual.html',1,'cv::saliency']]],
  ['statmodel',['StatModel',['../db/d7d/classcv_1_1ml_1_1StatModel.html',1,'cv::ml']]],
  ['stereobeliefpropagation',['StereoBeliefPropagation',['../de/d7a/classcv_1_1cuda_1_1StereoBeliefPropagation.html',1,'cv::cuda']]],
  ['stereobinarybm',['StereoBinaryBM',['../d7/d8e/classcv_1_1stereo_1_1StereoBinaryBM.html',1,'cv::stereo']]],
  ['stereobinarysgbm',['StereoBinarySGBM',['../d1/d9f/classcv_1_1stereo_1_1StereoBinarySGBM.html',1,'cv::stereo']]],
  ['stereobm',['StereoBM',['../d9/dba/classcv_1_1StereoBM.html',1,'cv']]],
  ['stereobm',['StereoBM',['../db/d8a/classcv_1_1cuda_1_1StereoBM.html',1,'cv::cuda']]],
  ['stereoconstantspacebp',['StereoConstantSpaceBP',['../d7/d09/classcv_1_1cuda_1_1StereoConstantSpaceBP.html',1,'cv::cuda']]],
  ['stereographicprojector',['StereographicProjector',['../d0/ddf/structcv_1_1detail_1_1StereographicProjector.html',1,'cv::detail']]],
  ['stereographicwarper',['StereographicWarper',['../d1/d3d/classcv_1_1detail_1_1StereographicWarper.html',1,'cv::detail']]],
  ['stereographicwarper',['StereographicWarper',['../d2/d5e/classcv_1_1StereographicWarper.html',1,'cv']]],
  ['stereomatcher',['StereoMatcher',['../d2/d6e/classcv_1_1StereoMatcher.html',1,'cv']]],
  ['stereomatcher',['StereoMatcher',['../d9/d07/classcv_1_1stereo_1_1StereoMatcher.html',1,'cv::stereo']]],
  ['stereosgbm',['StereoSGBM',['../d2/d85/classcv_1_1StereoSGBM.html',1,'cv']]],
  ['stitcher',['Stitcher',['../d2/d8d/classcv_1_1Stitcher.html',1,'cv']]],
  ['stream',['Stream',['../d9/df3/classcv_1_1cuda_1_1Stream.html',1,'cv::cuda']]],
  ['streamaccessor',['StreamAccessor',['../d6/df1/structcv_1_1cuda_1_1StreamAccessor.html',1,'cv::cuda']]],
  ['strongclassifierdirectselection',['StrongClassifierDirectSelection',['../d4/d1e/classcv_1_1StrongClassifierDirectSelection.html',1,'cv']]],
  ['structurededgedetection',['StructuredEdgeDetection',['../d8/d54/classcv_1_1ximgproc_1_1StructuredEdgeDetection.html',1,'cv::ximgproc']]],
  ['structuredlightpattern',['StructuredLightPattern',['../d9/dbb/classcv_1_1structured__light_1_1StructuredLightPattern.html',1,'cv::structured_light']]],
  ['subdiv2d',['Subdiv2D',['../df/dbf/classcv_1_1Subdiv2D.html',1,'cv']]],
  ['sum',['Sum',['../d8/d60/structcv_1_1cudev_1_1Sum.html',1,'cv::cudev']]],
  ['sumexprbody',['SumExprBody',['../dd/d33/structcv_1_1cudev_1_1SumExprBody.html',1,'cv::cudev']]],
  ['superpixellsc',['SuperpixelLSC',['../d5/da0/classcv_1_1ximgproc_1_1SuperpixelLSC.html',1,'cv::ximgproc']]],
  ['superpixelseeds',['SuperpixelSEEDS',['../df/d81/classcv_1_1ximgproc_1_1SuperpixelSEEDS.html',1,'cv::ximgproc']]],
  ['superpixelslic',['SuperpixelSLIC',['../d3/da9/classcv_1_1ximgproc_1_1SuperpixelSLIC.html',1,'cv::ximgproc']]],
  ['superresolution',['SuperResolution',['../d9/dd6/classcv_1_1superres_1_1SuperResolution.html',1,'cv::superres']]],
  ['surf',['SURF',['../d5/df7/classcv_1_1xfeatures2d_1_1SURF.html',1,'cv::xfeatures2d']]],
  ['surf_5fcuda',['SURF_CUDA',['../db/d06/classcv_1_1cuda_1_1SURF__CUDA.html',1,'cv::cuda']]],
  ['svd',['SVD',['../df/df7/classcv_1_1SVD.html',1,'cv']]],
  ['svm',['SVM',['../d1/d2d/classcv_1_1ml_1_1SVM.html',1,'cv::ml']]],
  ['svmsgd',['SVMSGD',['../de/d54/classcv_1_1ml_1_1SVMSGD.html',1,'cv::ml']]],
  ['symetriccensus',['SymetricCensus',['../dd/d24/classcv_1_1stereo_1_1SymetricCensus.html',1,'cv::stereo']]],
  ['syntheticsequencegenerator',['SyntheticSequenceGenerator',['../d1/dda/classcv_1_1bgsegm_1_1SyntheticSequenceGenerator.html',1,'cv::bgsegm']]]
];
