var searchData=
[
  ['tag',['tag',['../d3/d02/structcv_1_1datasets_1_1tag.html',1,'cv::datasets']]],
  ['tan_5ffunc',['tan_func',['../d7/d3e/structcv_1_1cudev_1_1tan__func.html',1,'cv::cudev']]],
  ['tan_5ffunc_3c_20double_20_3e',['tan_func&lt; double &gt;',['../db/dc4/structcv_1_1cudev_1_1tan__func_3_01double_01_4.html',1,'cv::cudev']]],
  ['tan_5ffunc_3c_20float_20_3e',['tan_func&lt; float &gt;',['../d5/d4e/structcv_1_1cudev_1_1tan__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['tan_5ffunc_3c_20schar_20_3e',['tan_func&lt; schar &gt;',['../d7/d9d/structcv_1_1cudev_1_1tan__func_3_01schar_01_4.html',1,'cv::cudev']]],
  ['tan_5ffunc_3c_20short_20_3e',['tan_func&lt; short &gt;',['../d6/dbd/structcv_1_1cudev_1_1tan__func_3_01short_01_4.html',1,'cv::cudev']]],
  ['tan_5ffunc_3c_20uchar_20_3e',['tan_func&lt; uchar &gt;',['../d2/d0d/structcv_1_1cudev_1_1tan__func_3_01uchar_01_4.html',1,'cv::cudev']]],
  ['tan_5ffunc_3c_20uint_20_3e',['tan_func&lt; uint &gt;',['../d6/d9e/structcv_1_1cudev_1_1tan__func_3_01uint_01_4.html',1,'cv::cudev']]],
  ['tan_5ffunc_3c_20ushort_20_3e',['tan_func&lt; ushort &gt;',['../d2/d63/structcv_1_1cudev_1_1tan__func_3_01ushort_01_4.html',1,'cv::cudev']]],
  ['tanh_5ffunc',['tanh_func',['../d5/d7b/structcv_1_1cudev_1_1tanh__func.html',1,'cv::cudev']]],
  ['tanh_5ffunc_3c_20double_20_3e',['tanh_func&lt; double &gt;',['../d4/d9f/structcv_1_1cudev_1_1tanh__func_3_01double_01_4.html',1,'cv::cudev']]],
  ['tanh_5ffunc_3c_20float_20_3e',['tanh_func&lt; float &gt;',['../dc/da0/structcv_1_1cudev_1_1tanh__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['tanh_5ffunc_3c_20schar_20_3e',['tanh_func&lt; schar &gt;',['../d5/dfc/structcv_1_1cudev_1_1tanh__func_3_01schar_01_4.html',1,'cv::cudev']]],
  ['tanh_5ffunc_3c_20short_20_3e',['tanh_func&lt; short &gt;',['../d8/db4/structcv_1_1cudev_1_1tanh__func_3_01short_01_4.html',1,'cv::cudev']]],
  ['tanh_5ffunc_3c_20uchar_20_3e',['tanh_func&lt; uchar &gt;',['../d8/d5a/structcv_1_1cudev_1_1tanh__func_3_01uchar_01_4.html',1,'cv::cudev']]],
  ['tanh_5ffunc_3c_20uint_20_3e',['tanh_func&lt; uint &gt;',['../df/dc6/structcv_1_1cudev_1_1tanh__func_3_01uint_01_4.html',1,'cv::cudev']]],
  ['tanh_5ffunc_3c_20ushort_20_3e',['tanh_func&lt; ushort &gt;',['../d6/d68/structcv_1_1cudev_1_1tanh__func_3_01ushort_01_4.html',1,'cv::cudev']]],
  ['tanhlayer',['TanHLayer',['../df/d66/classcv_1_1dnn_1_1TanHLayer.html',1,'cv::dnn']]],
  ['targetarchs',['TargetArchs',['../d9/dee/classcv_1_1cuda_1_1TargetArchs.html',1,'cv::cuda']]],
  ['template',['Template',['../d2/dc7/structcv_1_1linemod_1_1Template.html',1,'cv::linemod']]],
  ['templatematching',['TemplateMatching',['../d2/d58/classcv_1_1cuda_1_1TemplateMatching.html',1,'cv::cuda']]],
  ['termcriteria',['TermCriteria',['../d9/d5d/classcv_1_1TermCriteria.html',1,'cv']]],
  ['textdetector',['TextDetector',['../de/d25/classcv_1_1text_1_1TextDetector.html',1,'cv::text']]],
  ['textdetectorcnn',['TextDetectorCNN',['../d1/d66/classcv_1_1text_1_1TextDetectorCNN.html',1,'cv::text']]],
  ['texture',['Texture',['../db/d26/structcv_1_1face_1_1FacemarkAAM_1_1Model_1_1Texture.html',1,'cv::face::FacemarkAAM::Model']]],
  ['texture',['Texture',['../d0/dc5/structcv_1_1cudev_1_1Texture.html',1,'cv::cudev']]],
  ['texture2d',['Texture2D',['../d5/ddf/classcv_1_1ogl_1_1Texture2D.html',1,'cv::ogl']]],
  ['textureptr',['TexturePtr',['../d2/d09/structcv_1_1cudev_1_1TexturePtr.html',1,'cv::cudev']]],
  ['thash',['THash',['../da/dff/structTHash.html',1,'']]],
  ['thinplatesplineshapetransformer',['ThinPlateSplineShapeTransformer',['../dc/d18/classcv_1_1ThinPlateSplineShapeTransformer.html',1,'cv']]],
  ['threshbinaryfunc',['ThreshBinaryFunc',['../df/df5/structcv_1_1cudev_1_1ThreshBinaryFunc.html',1,'cv::cudev']]],
  ['threshbinaryinvfunc',['ThreshBinaryInvFunc',['../da/d5e/structcv_1_1cudev_1_1ThreshBinaryInvFunc.html',1,'cv::cudev']]],
  ['threshtozerofunc',['ThreshToZeroFunc',['../df/dd9/structcv_1_1cudev_1_1ThreshToZeroFunc.html',1,'cv::cudev']]],
  ['threshtozeroinvfunc',['ThreshToZeroInvFunc',['../d8/d7e/structcv_1_1cudev_1_1ThreshToZeroInvFunc.html',1,'cv::cudev']]],
  ['threshtruncfunc',['ThreshTruncFunc',['../d0/d44/structcv_1_1cudev_1_1ThreshTruncFunc.html',1,'cv::cudev']]],
  ['tickmeter',['TickMeter',['../d9/d6f/classcv_1_1TickMeter.html',1,'cv']]],
  ['timelapser',['Timelapser',['../dd/dac/classcv_1_1detail_1_1Timelapser.html',1,'cv::detail']]],
  ['timelapsercrop',['TimelapserCrop',['../df/db9/classcv_1_1detail_1_1TimelapserCrop.html',1,'cv::detail']]],
  ['timer',['Timer',['../df/d4a/classcv_1_1ocl_1_1Timer.html',1,'cv::ocl']]],
  ['tlsdata',['TLSData',['../d9/db0/classcv_1_1TLSData.html',1,'cv']]],
  ['tlsdata_3c_20cv_3a_3ainstr_3a_3anodedatatls_20_3e',['TLSData&lt; cv::instr::NodeDataTls &gt;',['../d9/db0/classcv_1_1TLSData.html',1,'cv']]],
  ['tlsdatacontainer',['TLSDataContainer',['../df/d21/classcv_1_1TLSDataContainer.html',1,'cv']]],
  ['tofilemotionwriter',['ToFileMotionWriter',['../dc/dc1/classcv_1_1videostab_1_1ToFileMotionWriter.html',1,'cv::videostab']]],
  ['tonemap',['Tonemap',['../d8/d5e/classcv_1_1Tonemap.html',1,'cv']]],
  ['tonemapdrago',['TonemapDrago',['../da/d53/classcv_1_1TonemapDrago.html',1,'cv']]],
  ['tonemapdurand',['TonemapDurand',['../da/d3d/classcv_1_1TonemapDurand.html',1,'cv']]],
  ['tonemapmantiuk',['TonemapMantiuk',['../de/d76/classcv_1_1TonemapMantiuk.html',1,'cv']]],
  ['tonemapreinhard',['TonemapReinhard',['../d0/dec/classcv_1_1TonemapReinhard.html',1,'cv']]],
  ['tr_5fchars',['TR_chars',['../d7/dc3/classcv_1_1datasets_1_1TR__chars.html',1,'cv::datasets']]],
  ['tr_5fcharsobj',['TR_charsObj',['../d8/d14/structcv_1_1datasets_1_1TR__charsObj.html',1,'cv::datasets']]],
  ['tr_5ficdar',['TR_icdar',['../d7/dfb/classcv_1_1datasets_1_1TR__icdar.html',1,'cv::datasets']]],
  ['tr_5ficdarobj',['TR_icdarObj',['../de/d04/structcv_1_1datasets_1_1TR__icdarObj.html',1,'cv::datasets']]],
  ['tr_5fsvt',['TR_svt',['../da/dc9/classcv_1_1datasets_1_1TR__svt.html',1,'cv::datasets']]],
  ['tr_5fsvtobj',['TR_svtObj',['../d3/dc5/structcv_1_1datasets_1_1TR__svtObj.html',1,'cv::datasets']]],
  ['track_5falov',['TRACK_alov',['../d8/d1c/classcv_1_1datasets_1_1TRACK__alov.html',1,'cv::datasets']]],
  ['track_5falovobj',['TRACK_alovObj',['../dd/d88/structcv_1_1datasets_1_1TRACK__alovObj.html',1,'cv::datasets']]],
  ['track_5fvot',['TRACK_vot',['../dc/d52/classcv_1_1datasets_1_1TRACK__vot.html',1,'cv::datasets']]],
  ['track_5fvotobj',['TRACK_votObj',['../d9/d36/structcv_1_1datasets_1_1TRACK__votObj.html',1,'cv::datasets']]],
  ['tracked_5fcv_5fmat',['tracked_cv_mat',['../d3/d73/structcv_1_1detail_1_1tracked__cv__mat.html',1,'cv::detail']]],
  ['tracked_5fcv_5fumat',['tracked_cv_umat',['../d1/df4/structcv_1_1detail_1_1tracked__cv__umat.html',1,'cv::detail']]],
  ['trackedobject',['TrackedObject',['../dc/de0/structcv_1_1DetectionBasedTracker_1_1TrackedObject.html',1,'cv::DetectionBasedTracker']]],
  ['tracker',['Tracker',['../d0/d0a/classcv_1_1Tracker.html',1,'cv']]],
  ['trackeradaboostingtargetstate',['TrackerAdaBoostingTargetState',['../d1/dd1/classcv_1_1TrackerStateEstimatorAdaBoosting_1_1TrackerAdaBoostingTargetState.html',1,'cv::TrackerStateEstimatorAdaBoosting']]],
  ['trackerboosting',['TrackerBoosting',['../d1/d1a/classcv_1_1TrackerBoosting.html',1,'cv']]],
  ['trackercsrt',['TrackerCSRT',['../d2/da2/classcv_1_1TrackerCSRT.html',1,'cv']]],
  ['trackerfeature',['TrackerFeature',['../d7/da2/classcv_1_1TrackerFeature.html',1,'cv']]],
  ['trackerfeaturefeature2d',['TrackerFeatureFeature2d',['../d3/d4c/classcv_1_1TrackerFeatureFeature2d.html',1,'cv']]],
  ['trackerfeaturehaar',['TrackerFeatureHAAR',['../d6/d00/classcv_1_1TrackerFeatureHAAR.html',1,'cv']]],
  ['trackerfeaturehog',['TrackerFeatureHOG',['../d2/da3/classcv_1_1TrackerFeatureHOG.html',1,'cv']]],
  ['trackerfeaturelbp',['TrackerFeatureLBP',['../dc/d73/classcv_1_1TrackerFeatureLBP.html',1,'cv']]],
  ['trackerfeatureset',['TrackerFeatureSet',['../dc/da7/classcv_1_1TrackerFeatureSet.html',1,'cv']]],
  ['trackergoturn',['TrackerGOTURN',['../d7/d4c/classcv_1_1TrackerGOTURN.html',1,'cv']]],
  ['trackerkcf',['TrackerKCF',['../d2/dff/classcv_1_1TrackerKCF.html',1,'cv']]],
  ['trackermedianflow',['TrackerMedianFlow',['../d7/d86/classcv_1_1TrackerMedianFlow.html',1,'cv']]],
  ['trackermil',['TrackerMIL',['../d0/d26/classcv_1_1TrackerMIL.html',1,'cv']]],
  ['trackermiltargetstate',['TrackerMILTargetState',['../d8/dd1/classcv_1_1TrackerStateEstimatorMILBoosting_1_1TrackerMILTargetState.html',1,'cv::TrackerStateEstimatorMILBoosting']]],
  ['trackermodel',['TrackerModel',['../d0/dfc/classcv_1_1TrackerModel.html',1,'cv']]],
  ['trackermosse',['TrackerMOSSE',['../d0/d02/classcv_1_1TrackerMOSSE.html',1,'cv']]],
  ['trackersampler',['TrackerSampler',['../da/d76/classcv_1_1TrackerSampler.html',1,'cv']]],
  ['trackersampleralgorithm',['TrackerSamplerAlgorithm',['../dc/d75/classcv_1_1TrackerSamplerAlgorithm.html',1,'cv']]],
  ['trackersamplercs',['TrackerSamplerCS',['../da/d3e/classcv_1_1TrackerSamplerCS.html',1,'cv']]],
  ['trackersamplercsc',['TrackerSamplerCSC',['../dc/d5c/classcv_1_1TrackerSamplerCSC.html',1,'cv']]],
  ['trackersamplerpf',['TrackerSamplerPF',['../d3/df4/classcv_1_1TrackerSamplerPF.html',1,'cv']]],
  ['trackerstateestimator',['TrackerStateEstimator',['../d2/db9/classcv_1_1TrackerStateEstimator.html',1,'cv']]],
  ['trackerstateestimatoradaboosting',['TrackerStateEstimatorAdaBoosting',['../de/df6/classcv_1_1TrackerStateEstimatorAdaBoosting.html',1,'cv']]],
  ['trackerstateestimatormilboosting',['TrackerStateEstimatorMILBoosting',['../d9/d20/classcv_1_1TrackerStateEstimatorMILBoosting.html',1,'cv']]],
  ['trackerstateestimatorsvm',['TrackerStateEstimatorSVM',['../d3/db6/classcv_1_1TrackerStateEstimatorSVM.html',1,'cv']]],
  ['trackertargetstate',['TrackerTargetState',['../dd/d9d/classcv_1_1TrackerTargetState.html',1,'cv']]],
  ['trackertld',['TrackerTLD',['../dc/d1c/classcv_1_1TrackerTLD.html',1,'cv']]],
  ['traindata',['TrainData',['../dc/d32/classcv_1_1ml_1_1TrainData.html',1,'cv::ml']]],
  ['transientareassegmentationmodule',['TransientAreasSegmentationModule',['../da/d6e/classcv_1_1bioinspired_1_1TransientAreasSegmentationModule.html',1,'cv::bioinspired']]],
  ['translationbasedlocaloutlierrejector',['TranslationBasedLocalOutlierRejector',['../dd/d13/classcv_1_1videostab_1_1TranslationBasedLocalOutlierRejector.html',1,'cv::videostab']]],
  ['transposebody',['TransposeBody',['../d2/d40/structcv_1_1cudev_1_1TransposeBody.html',1,'cv::cudev']]],
  ['transversemercatorprojector',['TransverseMercatorProjector',['../d5/df7/structcv_1_1detail_1_1TransverseMercatorProjector.html',1,'cv::detail']]],
  ['transversemercatorwarper',['TransverseMercatorWarper',['../df/d33/classcv_1_1TransverseMercatorWarper.html',1,'cv']]],
  ['transversemercatorwarper',['TransverseMercatorWarper',['../d4/d6b/classcv_1_1detail_1_1TransverseMercatorWarper.html',1,'cv::detail']]],
  ['true',['True',['../d3/d87/classcvflann_1_1True.html',1,'cvflann']]],
  ['tuple_5fwrap_5fhelper',['tuple_wrap_helper',['../d6/d67/structcv_1_1detail_1_1tuple__wrap__helper.html',1,'cv::detail']]],
  ['tuple_5fwrap_5fhelper_3c_20std_3a_3atuple_3c_20objs_2e_2e_2e_20_3e_20_3e',['tuple_wrap_helper&lt; std::tuple&lt; Objs... &gt; &gt;',['../de/d5f/structcv_1_1detail_1_1tuple__wrap__helper_3_01std_1_1tuple_3_01Objs_8_8_8_01_4_01_4.html',1,'cv::detail']]],
  ['tupletraits',['TupleTraits',['../dd/d08/structcv_1_1cudev_1_1TupleTraits.html',1,'cv::cudev']]],
  ['tupletraits_3c_20tuple_3c_20p0_2c_20p1_2c_20p2_2c_20p3_2c_20p4_2c_20p5_2c_20p6_2c_20p7_2c_20p8_2c_20p9_20_3e_20_3e',['TupleTraits&lt; tuple&lt; P0, P1, P2, P3, P4, P5, P6, P7, P8, P9 &gt; &gt;',['../d2/dae/structcv_1_1cudev_1_1TupleTraits_3_01tuple_3_01P0_00_01P1_00_01P2_00_01P3_00_01P4_00_01P5_00_01P41642a2d25b95a5ddb87ca2004b28336.html',1,'cv::cudev']]],
  ['twopassstabilizer',['TwoPassStabilizer',['../d8/d9c/classcv_1_1videostab_1_1TwoPassStabilizer.html',1,'cv::videostab']]],
  ['type_5flist_5findex',['type_list_index',['../d4/d46/structcv_1_1util_1_1type__list__index.html',1,'cv::util']]],
  ['type_5flist_5findex_5fhelper',['type_list_index_helper',['../d1/d34/structcv_1_1util_1_1detail_1_1type__list__index__helper.html',1,'cv::util::detail']]],
  ['type_5flist_5findex_5fhelper_3c_20i_2c_20target_2c_20first_20_3e',['type_list_index_helper&lt; I, Target, First &gt;',['../df/dfa/structcv_1_1util_1_1detail_1_1type__list__index__helper_3_01I_00_01Target_00_01First_01_4.html',1,'cv::util::detail']]],
  ['typed_5fbase_5fany_5fpolicy',['typed_base_any_policy',['../d5/d0f/structcvflann_1_1anyimpl_1_1typed__base__any__policy.html',1,'cvflann::anyimpl']]],
  ['typesequals',['TypesEquals',['../df/d71/structcv_1_1cudev_1_1TypesEquals.html',1,'cv::cudev']]],
  ['typesequals_3c_20a_2c_20a_20_3e',['TypesEquals&lt; A, A &gt;',['../df/dbf/structcv_1_1cudev_1_1TypesEquals_3_01A_00_01A_01_4.html',1,'cv::cudev']]],
  ['typetraits',['TypeTraits',['../d7/d97/structcv_1_1cudev_1_1TypeTraits.html',1,'cv::cudev']]]
];
