var searchData=
[
  ['ukfsystemmodel',['UkfSystemModel',['../da/d2b/classcv_1_1tracking_1_1UkfSystemModel.html',1,'cv::tracking']]],
  ['umat',['UMat',['../d7/d45/classcv_1_1UMat.html',1,'cv']]],
  ['umatdata',['UMatData',['../db/d58/structcv_1_1UMatData.html',1,'cv']]],
  ['unary_5ffunction',['unary_function',['../df/d11/structcv_1_1cudev_1_1unary__function.html',1,'cv::cudev']]],
  ['unary_5ffunction_3c_20double_2c_20double_20_3e',['unary_function&lt; double, double &gt;',['../df/d11/structcv_1_1cudev_1_1unary__function.html',1,'cv::cudev']]],
  ['unary_5ffunction_3c_20float_2c_20float_20_3e',['unary_function&lt; float, float &gt;',['../df/d11/structcv_1_1cudev_1_1unary__function.html',1,'cv::cudev']]],
  ['unary_5ffunction_3c_20float_2c_20short_20_3e',['unary_function&lt; float, short &gt;',['../df/d11/structcv_1_1cudev_1_1unary__function.html',1,'cv::cudev']]],
  ['unary_5ffunction_3c_20int_2c_20float_20_3e',['unary_function&lt; int, float &gt;',['../df/d11/structcv_1_1cudev_1_1unary__function.html',1,'cv::cudev']]],
  ['unary_5ffunction_3c_20int_2c_20int_20_3e',['unary_function&lt; int, int &gt;',['../df/d11/structcv_1_1cudev_1_1unary__function.html',1,'cv::cudev']]],
  ['unary_5ffunction_3c_20op_3a_3afirst_5fargument_5ftype_2c_20op_3a_3aresult_5ftype_20_3e',['unary_function&lt; Op::first_argument_type, Op::result_type &gt;',['../df/d11/structcv_1_1cudev_1_1unary__function.html',1,'cv::cudev']]],
  ['unary_5ffunction_3c_20op_3a_3asecond_5fargument_5ftype_2c_20op_3a_3aresult_5ftype_20_3e',['unary_function&lt; Op::second_argument_type, Op::result_type &gt;',['../df/d11/structcv_1_1cudev_1_1unary__function.html',1,'cv::cudev']]],
  ['unary_5ffunction_3c_20predicate_3a_3aargument_5ftype_2c_20predicate_3a_3aresult_5ftype_20_3e',['unary_function&lt; Predicate::argument_type, Predicate::result_type &gt;',['../df/d11/structcv_1_1cudev_1_1unary__function.html',1,'cv::cudev']]],
  ['unary_5ffunction_3c_20schar_2c_20float_20_3e',['unary_function&lt; schar, float &gt;',['../df/d11/structcv_1_1cudev_1_1unary__function.html',1,'cv::cudev']]],
  ['unary_5ffunction_3c_20schar_2c_20schar_20_3e',['unary_function&lt; schar, schar &gt;',['../df/d11/structcv_1_1cudev_1_1unary__function.html',1,'cv::cudev']]],
  ['unary_5ffunction_3c_20short_2c_20float_20_3e',['unary_function&lt; short, float &gt;',['../df/d11/structcv_1_1cudev_1_1unary__function.html',1,'cv::cudev']]],
  ['unary_5ffunction_3c_20short_2c_20short_20_3e',['unary_function&lt; short, short &gt;',['../df/d11/structcv_1_1cudev_1_1unary__function.html',1,'cv::cudev']]],
  ['unary_5ffunction_3c_20t_2c_20d_20_3e',['unary_function&lt; T, D &gt;',['../df/d11/structcv_1_1cudev_1_1unary__function.html',1,'cv::cudev']]],
  ['unary_5ffunction_3c_20t_2c_20functional_5fdetail_3a_3afloattype_3c_20t_20_3e_3a_3atype_20_3e',['unary_function&lt; T, functional_detail::FloatType&lt; T &gt;::type &gt;',['../df/d11/structcv_1_1cudev_1_1unary__function.html',1,'cv::cudev']]],
  ['unary_5ffunction_3c_20t_2c_20makevec_3c_20uchar_2c_20vectraits_3c_20t_20_3e_3a_3acn_20_3e_3a_3atype_20_3e',['unary_function&lt; T, MakeVec&lt; uchar, VecTraits&lt; T &gt;::cn &gt;::type &gt;',['../df/d11/structcv_1_1cudev_1_1unary__function.html',1,'cv::cudev']]],
  ['unary_5ffunction_3c_20t_2c_20t_20_3e',['unary_function&lt; T, T &gt;',['../df/d11/structcv_1_1cudev_1_1unary__function.html',1,'cv::cudev']]],
  ['unary_5ffunction_3c_20uchar_2c_20float_20_3e',['unary_function&lt; uchar, float &gt;',['../df/d11/structcv_1_1cudev_1_1unary__function.html',1,'cv::cudev']]],
  ['unary_5ffunction_3c_20uchar_2c_20uchar_20_3e',['unary_function&lt; uchar, uchar &gt;',['../df/d11/structcv_1_1cudev_1_1unary__function.html',1,'cv::cudev']]],
  ['unary_5ffunction_3c_20uint_2c_20float_20_3e',['unary_function&lt; uint, float &gt;',['../df/d11/structcv_1_1cudev_1_1unary__function.html',1,'cv::cudev']]],
  ['unary_5ffunction_3c_20uint_2c_20uint_20_3e',['unary_function&lt; uint, uint &gt;',['../df/d11/structcv_1_1cudev_1_1unary__function.html',1,'cv::cudev']]],
  ['unary_5ffunction_3c_20ushort_2c_20float_20_3e',['unary_function&lt; ushort, float &gt;',['../df/d11/structcv_1_1cudev_1_1unary__function.html',1,'cv::cudev']]],
  ['unary_5ffunction_3c_20ushort_2c_20ushort_20_3e',['unary_function&lt; ushort, ushort &gt;',['../df/d11/structcv_1_1cudev_1_1unary__function.html',1,'cv::cudev']]],
  ['unarynegate',['UnaryNegate',['../d2/d83/structcv_1_1cudev_1_1UnaryNegate.html',1,'cv::cudev']]],
  ['unarytransformptr',['UnaryTransformPtr',['../dd/d01/structcv_1_1cudev_1_1UnaryTransformPtr.html',1,'cv::cudev']]],
  ['unarytransformptrsz',['UnaryTransformPtrSz',['../d0/db7/structcv_1_1cudev_1_1UnaryTransformPtrSz.html',1,'cv::cudev']]],
  ['unarytupleadapter',['UnaryTupleAdapter',['../d4/d57/structcv_1_1cudev_1_1UnaryTupleAdapter.html',1,'cv::cudev']]],
  ['uniquerandom',['UniqueRandom',['../d9/de3/classcvflann_1_1UniqueRandom.html',1,'cvflann']]],
  ['uniqueresultset',['UniqueResultSet',['../d4/dca/classcvflann_1_1UniqueResultSet.html',1,'cvflann']]],
  ['unscentedkalmanfilter',['UnscentedKalmanFilter',['../de/d72/classcv_1_1tracking_1_1UnscentedKalmanFilter.html',1,'cv::tracking']]],
  ['unscentedkalmanfilterparams',['UnscentedKalmanFilterParams',['../da/d73/classcv_1_1tracking_1_1UnscentedKalmanFilterParams.html',1,'cv::tracking']]],
  ['untypedmatrix',['UntypedMatrix',['../d4/d5a/classcvflann_1_1UntypedMatrix.html',1,'cvflann']]]
];
