var searchData=
[
  ['daisy',['DAISY',['../d9/d37/classcv_1_1xfeatures2d_1_1DAISY.html',1,'cv::xfeatures2d']]],
  ['data',['Data',['../de/d4f/structcv_1_1face_1_1FacemarkAAM_1_1Data.html',1,'cv::face::FacemarkAAM']]],
  ['datadepth',['DataDepth',['../d7/d0e/classcv_1_1DataDepth.html',1,'cv']]],
  ['dataset',['Dataset',['../d9/d2e/classcv_1_1datasets_1_1Dataset.html',1,'cv::datasets']]],
  ['datatype',['Datatype',['../d4/dbd/structcvflann_1_1Datatype.html',1,'cvflann']]],
  ['datatype',['DataType',['../d0/d3a/classcv_1_1DataType.html',1,'cv']]],
  ['datatype_3c_20char_20_3e',['Datatype&lt; char &gt;',['../d3/df4/structcvflann_1_1Datatype_3_01char_01_4.html',1,'cvflann']]],
  ['datatype_3c_20double_20_3e',['Datatype&lt; double &gt;',['../d2/d8d/structcvflann_1_1Datatype_3_01double_01_4.html',1,'cvflann']]],
  ['datatype_3c_20float_20_3e',['Datatype&lt; float &gt;',['../dd/d42/structcvflann_1_1Datatype_3_01float_01_4.html',1,'cvflann']]],
  ['datatype_3c_20short_20_3e',['Datatype&lt; short &gt;',['../db/de5/structcvflann_1_1Datatype_3_01short_01_4.html',1,'cvflann']]],
  ['datatype_3c_20unsigned_20char_20_3e',['Datatype&lt; unsigned char &gt;',['../d3/dea/structcvflann_1_1Datatype_3_01unsigned_01char_01_4.html',1,'cvflann']]],
  ['datatype_3c_20unsigned_20short_20_3e',['Datatype&lt; unsigned short &gt;',['../dc/dbe/structcvflann_1_1Datatype_3_01unsigned_01short_01_4.html',1,'cvflann']]],
  ['dct2d',['DCT2D',['../d5/d57/structcv_1_1hal_1_1DCT2D.html',1,'cv::hal']]],
  ['deblurerbase',['DeblurerBase',['../dd/d05/classcv_1_1videostab_1_1DeblurerBase.html',1,'cv::videostab']]],
  ['deconvolutionlayer',['DeconvolutionLayer',['../dd/d77/classcv_1_1dnn_1_1DeconvolutionLayer.html',1,'cv::dnn']]],
  ['defaultcopypolicy',['DefaultCopyPolicy',['../d8/dc2/structcv_1_1cudev_1_1DefaultCopyPolicy.html',1,'cv::cudev']]],
  ['defaultdeleter_3c_20cvcapture_20_3e',['DefaultDeleter&lt; CvCapture &gt;',['../d0/d90/structcv_1_1DefaultDeleter_3_01CvCapture_01_4.html',1,'cv']]],
  ['defaultdeleter_3c_20cvhaarclassifiercascade_20_3e',['DefaultDeleter&lt; CvHaarClassifierCascade &gt;',['../d9/ddf/structcv_1_1DefaultDeleter_3_01CvHaarClassifierCascade_01_4.html',1,'cv']]],
  ['defaultdeleter_3c_20cvvideowriter_20_3e',['DefaultDeleter&lt; CvVideoWriter &gt;',['../d2/d37/structcv_1_1DefaultDeleter_3_01CvVideoWriter_01_4.html',1,'cv']]],
  ['defaultglobreducepolicy',['DefaultGlobReducePolicy',['../d2/d04/structcv_1_1cudev_1_1DefaultGlobReducePolicy.html',1,'cv::cudev']]],
  ['defaulthistogrampolicy',['DefaultHistogramPolicy',['../d4/d2b/structcv_1_1cudev_1_1DefaultHistogramPolicy.html',1,'cv::cudev']]],
  ['defaultreducetovecpolicy',['DefaultReduceToVecPolicy',['../d3/dd7/structcv_1_1cudev_1_1DefaultReduceToVecPolicy.html',1,'cv::cudev']]],
  ['defaultsplitmergepolicy',['DefaultSplitMergePolicy',['../d9/d3a/structcv_1_1cudev_1_1DefaultSplitMergePolicy.html',1,'cv::cudev']]],
  ['defaulttransformpolicy',['DefaultTransformPolicy',['../db/db3/structcv_1_1cudev_1_1DefaultTransformPolicy.html',1,'cv::cudev']]],
  ['defaulttransposepolicy',['DefaultTransposePolicy',['../dd/d44/structcv_1_1cudev_1_1DefaultTransposePolicy.html',1,'cv::cudev']]],
  ['denseopticalflow',['DenseOpticalFlow',['../df/dde/classcv_1_1DenseOpticalFlow.html',1,'cv']]],
  ['denseopticalflow',['DenseOpticalFlow',['../d6/d4a/classcv_1_1cuda_1_1DenseOpticalFlow.html',1,'cv::cuda']]],
  ['denseopticalflowext',['DenseOpticalFlowExt',['../d1/d21/classcv_1_1superres_1_1DenseOpticalFlowExt.html',1,'cv::superres']]],
  ['densepyrlkopticalflow',['DensePyrLKOpticalFlow',['../d0/da4/classcv_1_1cuda_1_1DensePyrLKOpticalFlow.html',1,'cv::cuda']]],
  ['depthcleaner',['DepthCleaner',['../d9/d5e/classcv_1_1rgbd_1_1DepthCleaner.html',1,'cv::rgbd']]],
  ['depthnormal',['DepthNormal',['../d7/d47/classcv_1_1linemod_1_1DepthNormal.html',1,'cv::linemod']]],
  ['derivxptr',['DerivXPtr',['../df/d8b/structcv_1_1cudev_1_1DerivXPtr.html',1,'cv::cudev']]],
  ['derivxptrsz',['DerivXPtrSz',['../db/d58/structcv_1_1cudev_1_1DerivXPtrSz.html',1,'cv::cudev']]],
  ['derivyptr',['DerivYPtr',['../dc/d51/structcv_1_1cudev_1_1DerivYPtr.html',1,'cv::cudev']]],
  ['derivyptrsz',['DerivYPtrSz',['../d2/dfc/structcv_1_1cudev_1_1DerivYPtrSz.html',1,'cv::cudev']]],
  ['descriptorcollection',['DescriptorCollection',['../d4/dac/classcv_1_1DescriptorMatcher_1_1DescriptorCollection.html',1,'cv::DescriptorMatcher']]],
  ['descriptorextractor',['descriptorExtractor',['../d7/d8d/classcv_1_1cnn__3dobj_1_1descriptorExtractor.html',1,'cv::cnn_3dobj']]],
  ['descriptormatcher',['DescriptorMatcher',['../db/d39/classcv_1_1DescriptorMatcher.html',1,'cv']]],
  ['descriptormatcher',['DescriptorMatcher',['../dd/dc5/classcv_1_1cuda_1_1DescriptorMatcher.html',1,'cv::cuda']]],
  ['detectionbasedtracker',['DetectionBasedTracker',['../db/de9/classcv_1_1DetectionBasedTracker.html',1,'cv']]],
  ['detectionoutputlayer',['DetectionOutputLayer',['../da/dbd/classcv_1_1dnn_1_1DetectionOutputLayer.html',1,'cv::dnn']]],
  ['detectionroi',['DetectionROI',['../d3/d34/structcv_1_1DetectionROI.html',1,'cv']]],
  ['detector',['Detector',['../de/db6/classcv_1_1Detector.html',1,'cv']]],
  ['detector',['Detector',['../d7/d07/classcv_1_1linemod_1_1Detector.html',1,'cv::linemod']]],
  ['detectorparameters',['DetectorParameters',['../d1/dcd/structcv_1_1aruco_1_1DetectorParameters.html',1,'cv::aruco']]],
  ['device',['Device',['../d7/d9f/classcv_1_1ocl_1_1Device.html',1,'cv::ocl']]],
  ['deviceinfo',['DeviceInfo',['../d7/d7c/classcv_1_1cuda_1_1DeviceInfo.html',1,'cv::cuda']]],
  ['dft',['DFT',['../dc/de5/classcv_1_1cuda_1_1DFT.html',1,'cv::cuda']]],
  ['dft1d',['DFT1D',['../d8/d03/structcv_1_1hal_1_1DFT1D.html',1,'cv::hal']]],
  ['dft2d',['DFT2D',['../d6/d77/structcv_1_1hal_1_1DFT2D.html',1,'cv::hal']]],
  ['dict',['Dict',['../d9/d2b/classcv_1_1dnn_1_1Dict.html',1,'cv::dnn']]],
  ['dictionary',['Dictionary',['../d5/d0b/classcv_1_1aruco_1_1Dictionary.html',1,'cv::aruco']]],
  ['dictvalue',['DictValue',['../d4/db3/structcv_1_1dnn_1_1DictValue.html',1,'cv::dnn']]],
  ['direction_5ffunc',['direction_func',['../d3/d97/structcv_1_1cudev_1_1direction__func.html',1,'cv::cudev']]],
  ['disableif',['DisableIf',['../df/d27/structcv_1_1cudev_1_1DisableIf.html',1,'cv::cudev']]],
  ['disjointsets',['DisjointSets',['../dc/d3e/classcv_1_1detail_1_1DisjointSets.html',1,'cv::detail']]],
  ['disopticalflow',['DISOpticalFlow',['../de/d4f/classcv_1_1DISOpticalFlow.html',1,'cv']]],
  ['disparitybilateralfilter',['DisparityBilateralFilter',['../d8/d4f/classcv_1_1cuda_1_1DisparityBilateralFilter.html',1,'cv::cuda']]],
  ['disparityfilter',['DisparityFilter',['../db/d72/classcv_1_1ximgproc_1_1DisparityFilter.html',1,'cv::ximgproc']]],
  ['disparitywlsfilter',['DisparityWLSFilter',['../d9/d51/classcv_1_1ximgproc_1_1DisparityWLSFilter.html',1,'cv::ximgproc']]],
  ['distindex',['DistIndex',['../d0/d28/structcvflann_1_1UniqueResultSet_1_1DistIndex.html',1,'cvflann::UniqueResultSet']]],
  ['divides',['divides',['../de/d2a/structcv_1_1cudev_1_1divides.html',1,'cv::cudev']]],
  ['dmatch',['DMatch',['../d4/de0/classcv_1_1DMatch.html',1,'cv']]],
  ['downhillsolver',['DownhillSolver',['../d4/d43/classcv_1_1DownhillSolver.html',1,'cv']]],
  ['dpmdetector',['DPMDetector',['../df/dba/classcv_1_1dpm_1_1DPMDetector.html',1,'cv::dpm']]],
  ['dpseamfinder',['DpSeamFinder',['../d0/dd5/classcv_1_1detail_1_1DpSeamFinder.html',1,'cv::detail']]],
  ['drawlinesmatchesflags',['DrawLinesMatchesFlags',['../d8/d6f/structcv_1_1line__descriptor_1_1DrawLinesMatchesFlags.html',1,'cv::line_descriptor']]],
  ['dtfilter',['DTFilter',['../d3/d9d/classcv_1_1ximgproc_1_1DTFilter.html',1,'cv::ximgproc']]],
  ['dtrees',['DTrees',['../d8/d89/classcv_1_1ml_1_1DTrees.html',1,'cv::ml']]],
  ['dualtvl1opticalflow',['DualTVL1OpticalFlow',['../d6/db1/classcv_1_1superres_1_1DualTVL1OpticalFlow.html',1,'cv::superres']]],
  ['dualtvl1opticalflow',['DualTVL1OpticalFlow',['../dc/d4d/classcv_1_1optflow_1_1DualTVL1OpticalFlow.html',1,'cv::optflow']]],
  ['dynamicbitset',['DynamicBitset',['../d1/d73/classcvflann_1_1DynamicBitset.html',1,'cvflann']]],
  ['dynamicsharedmem',['DynamicSharedMem',['../d3/d2b/structcv_1_1cudev_1_1DynamicSharedMem.html',1,'cv::cudev']]],
  ['dynamicsharedmem_3c_20double_20_3e',['DynamicSharedMem&lt; double &gt;',['../db/d28/structcv_1_1cudev_1_1DynamicSharedMem_3_01double_01_4.html',1,'cv::cudev']]]
];
