var searchData=
[
  ['object',['Object',['../de/d47/structcv_1_1datasets_1_1Object.html',1,'cv::datasets']]],
  ['object',['object',['../d4/d36/structcv_1_1dnn__objdetect_1_1object.html',1,'cv::dnn_objdetect']]],
  ['objectdetection',['ObjectDetection',['../d7/de4/structcv_1_1dpm_1_1DPMDetector_1_1ObjectDetection.html',1,'cv::dpm::DPMDetector']]],
  ['objectfactory',['ObjectFactory',['../df/dd6/classcvflann_1_1ObjectFactory.html',1,'cvflann']]],
  ['objectness',['Objectness',['../d1/d82/classcv_1_1saliency_1_1Objectness.html',1,'cv::saliency']]],
  ['objectnessbing',['ObjectnessBING',['../db/d63/classcv_1_1saliency_1_1ObjectnessBING.html',1,'cv::saliency']]],
  ['ocrbeamsearchdecoder',['OCRBeamSearchDecoder',['../da/d07/classcv_1_1text_1_1OCRBeamSearchDecoder.html',1,'cv::text']]],
  ['ocrhmmdecoder',['OCRHMMDecoder',['../d0/d74/classcv_1_1text_1_1OCRHMMDecoder.html',1,'cv::text']]],
  ['ocrholisticwordrecognizer',['OCRHolisticWordRecognizer',['../d0/d8f/classcv_1_1text_1_1OCRHolisticWordRecognizer.html',1,'cv::text']]],
  ['ocrtesseract',['OCRTesseract',['../d7/ddc/classcv_1_1text_1_1OCRTesseract.html',1,'cv::text']]],
  ['ocvcallhelper',['OCVCallHelper',['../d9/d23/structcv_1_1detail_1_1OCVCallHelper.html',1,'cv::detail']]],
  ['ocvcallhelper_3c_20impl_2c_20k_3a_3ainargs_2c_20k_3a_3aoutargs_20_3e',['OCVCallHelper&lt; Impl, K::InArgs, K::OutArgs &gt;',['../d9/d23/structcv_1_1detail_1_1OCVCallHelper.html',1,'cv::detail']]],
  ['ocvcallhelper_3c_20impl_2c_20std_3a_3atuple_3c_20ins_2e_2e_2e_20_3e_2c_20std_3a_3atuple_3c_20outs_2e_2e_2e_20_3e_20_3e',['OCVCallHelper&lt; Impl, std::tuple&lt; Ins... &gt;, std::tuple&lt; Outs... &gt; &gt;',['../da/d5a/structcv_1_1detail_1_1OCVCallHelper_3_01Impl_00_01std_1_1tuple_3_01Ins_8_8_8_01_4_00_01std_1_1tuple_3_01Outs_8_8_8_01_4_01_4.html',1,'cv::detail']]],
  ['odometry',['Odometry',['../df/ddc/classcv_1_1rgbd_1_1Odometry.html',1,'cv::rgbd']]],
  ['odometryframe',['OdometryFrame',['../d7/d15/structcv_1_1rgbd_1_1OdometryFrame.html',1,'cv::rgbd']]],
  ['onepassstabilizer',['OnePassStabilizer',['../d3/db1/classcv_1_1videostab_1_1OnePassStabilizer.html',1,'cv::videostab']]],
  ['oplandiplparvoparameters',['OPLandIplParvoParameters',['../d0/dc1/structcv_1_1bioinspired_1_1RetinaParameters_1_1OPLandIplParvoParameters.html',1,'cv::bioinspired::RetinaParameters']]],
  ['opticalflowdual_5ftvl1',['OpticalFlowDual_TVL1',['../d6/d39/classcv_1_1cuda_1_1OpticalFlowDual__TVL1.html',1,'cv::cuda']]],
  ['opticalflowpcaflow',['OpticalFlowPCAFlow',['../d1/da2/classcv_1_1optflow_1_1OpticalFlowPCAFlow.html',1,'cv::optflow']]],
  ['optional',['optional',['../d1/dec/classcv_1_1util_1_1optional.html',1,'cv::util']]],
  ['optional_5flock_5fguard',['optional_lock_guard',['../d3/de8/classcv_1_1utils_1_1optional__lock__guard.html',1,'cv::utils']]],
  ['optional_5fshared_5flock_5fguard',['optional_shared_lock_guard',['../d2/ddd/classcv_1_1utils_1_1optional__shared__lock__guard.html',1,'cv::utils']]],
  ['or_5fimagenet',['OR_imagenet',['../db/df7/classcv_1_1datasets_1_1OR__imagenet.html',1,'cv::datasets']]],
  ['or_5fimagenetobj',['OR_imagenetObj',['../de/d3f/structcv_1_1datasets_1_1OR__imagenetObj.html',1,'cv::datasets']]],
  ['or_5fmnist',['OR_mnist',['../d9/d92/classcv_1_1datasets_1_1OR__mnist.html',1,'cv::datasets']]],
  ['or_5fmnistobj',['OR_mnistObj',['../d0/d2c/structcv_1_1datasets_1_1OR__mnistObj.html',1,'cv::datasets']]],
  ['or_5fpascal',['OR_pascal',['../d4/d7e/classcv_1_1datasets_1_1OR__pascal.html',1,'cv::datasets']]],
  ['or_5fpascalobj',['OR_pascalObj',['../d0/db6/structcv_1_1datasets_1_1OR__pascalObj.html',1,'cv::datasets']]],
  ['or_5fsun',['OR_sun',['../da/d69/classcv_1_1datasets_1_1OR__sun.html',1,'cv::datasets']]],
  ['or_5fsunobj',['OR_sunObj',['../d8/d74/structcv_1_1datasets_1_1OR__sunObj.html',1,'cv::datasets']]],
  ['orb',['ORB',['../db/d95/classcv_1_1ORB.html',1,'cv']]],
  ['orb',['ORB',['../da/d44/classcv_1_1cuda_1_1ORB.html',1,'cv::cuda']]],
  ['out_5ftag',['Out_Tag',['../dd/d92/structcv_1_1Out__Tag.html',1,'cv']]]
];
