var searchData=
[
  ['cuda_20module_20introduction',['CUDA Module Introduction',['../d2/dbc/cuda_intro.html',1,'']]],
  ['color_20conversions',['Color conversions',['../de/d25/imgproc_color_conversions.html',1,'']]],
  ['cross_20compilation_20for_20arm_20based_20linux_20systems',['Cross compilation for ARM based Linux systems',['../d0/d76/tutorial_arm_crosscompile_with_cmake.html',1,'tutorial_table_of_content_introduction']]],
  ['calibration_20with_20aruco_20and_20charuco',['Calibration with ArUco and ChArUco',['../da/d13/tutorial_aruco_calibration.html',1,'tutorial_table_of_content_aruco']]],
  ['changing_20the_20contrast_20and_20brightness_20of_20an_20image_21',['Changing the contrast and brightness of an image!',['../d3/dc1/tutorial_basic_linear_transform.html',1,'tutorial_table_of_content_core']]],
  ['creating_20bounding_20boxes_20and_20circles_20for_20contours',['Creating Bounding boxes and circles for contours',['../da/d0c/tutorial_bounding_rects_circles.html',1,'tutorial_table_of_content_imgproc']]],
  ['creating_20bounding_20rotated_20boxes_20and_20ellipses_20for_20contours',['Creating Bounding rotated boxes and ellipses for contours',['../de/d62/tutorial_bounding_rotated_ellipses.html',1,'tutorial_table_of_content_imgproc']]],
  ['camera_20calibration_20with_20opencv',['Camera calibration With OpenCV',['../d4/d94/tutorial_camera_calibration.html',1,'tutorial_table_of_content_calib3d']]],
  ['camera_20calibration_20with_20square_20chessboard',['Camera calibration with square chessboard',['../dc/d43/tutorial_camera_calibration_square_chess.html',1,'tutorial_table_of_content_calib3d']]],
  ['canny_20edge_20detector',['Canny Edge Detector',['../da/d5c/tutorial_canny_detector.html',1,'tutorial_table_of_content_imgproc']]],
  ['capture_20gray_20code_20pattern_20tutorial',['Capture Gray code pattern tutorial',['../db/d56/tutorial_capture_graycode_pattern.html',1,'tutorial_structured_light']]],
  ['capture_20sinusoidal_20pattern_20tutorial',['Capture Sinusoidal pattern tutorial',['../d0/de8/tutorial_capture_sinusoidal_pattern.html',1,'tutorial_structured_light']]],
  ['cascade_20classifier',['Cascade Classifier',['../db/d28/tutorial_cascade_classifier.html',1,'tutorial_table_of_content_objdetect']]],
  ['creating_20widgets',['Creating Widgets',['../d2/d64/tutorial_creating_widgets.html',1,'tutorial_table_of_content_viz']]],
  ['cross_20referencing_20opencv_20from_20other_20doxygen_20projects',['Cross referencing OpenCV from other Doxygen projects',['../d3/dff/tutorial_cross_referencing.html',1,'tutorial_table_of_content_introduction']]],
  ['customizing_20the_20cn_20tracker',['Customizing the CN Tracker',['../dc/db8/tutorial_customizing_cn_tracker.html',1,'tutorial_contrib_root']]],
  ['custom_20deep_20learning_20layers_20support',['Custom deep learning layers support',['../dc/db1/tutorial_dnn_custom_layers.html',1,'tutorial_table_of_content_dnn']]],
  ['classify',['Classify',['../df/d38/tutorial_feature_classification.html',1,'tutorial_table_of_content_cnn_3dobj']]],
  ['creating_20your_20own_20corner_20detector',['Creating your own corner detector',['../d9/dbc/tutorial_generic_corner_detector.html',1,'tutorial_table_of_content_features2d']]],
  ['creating_20groups',['Creating Groups',['../d1/d8b/tutorial_hdf_create_groups.html',1,'tutorial_table_of_content_hdf']]],
  ['creating_2c_20writing_20and_20reading_20datasets',['Creating, Writing and Reading Datasets',['../d4/d93/tutorial_hdf_create_read_write_datasets.html',1,'tutorial_table_of_content_hdf']]],
  ['creating_20a_203d_20histogram',['Creating a 3D histogram',['../d1/d1d/tutorial_histo3D.html',1,'tutorial_table_of_content_viz']]],
  ['convex_20hull',['Convex Hull',['../d7/d1d/tutorial_hull.html',1,'tutorial_table_of_content_imgproc']]],
  ['canny_20edge_20detection',['Canny Edge Detection',['../d7/de1/tutorial_js_canny.html',1,'tutorial_js_table_of_contents_imgproc']]],
  ['changing_20colorspaces',['Changing Colorspaces',['../db/d64/tutorial_js_colorspaces.html',1,'tutorial_js_table_of_contents_imgproc']]],
  ['contour_20features',['Contour Features',['../dc/dcf/tutorial_js_contour_features.html',1,'tutorial_js_table_of_contents_contours']]],
  ['contour_20properties',['Contour Properties',['../da/dc1/tutorial_js_contour_properties.html',1,'tutorial_js_table_of_contents_contours']]],
  ['contours_20_3a_20getting_20started',['Contours : Getting Started',['../d5/daa/tutorial_js_contours_begin.html',1,'tutorial_js_table_of_contents_contours']]],
  ['contours_20hierarchy',['Contours Hierarchy',['../da/d0a/tutorial_js_contours_hierarchy.html',1,'tutorial_js_table_of_contents_contours']]],
  ['contours_20_3a_20more_20functions',['Contours : More Functions',['../d8/d1c/tutorial_js_contours_more_functions.html',1,'tutorial_js_table_of_contents_contours']]],
  ['contours_20in_20opencv_2ejs',['Contours in OpenCV.js',['../d0/d43/tutorial_js_table_of_contents_contours.html',1,'tutorial_js_table_of_contents_imgproc']]],
  ['core_20operations',['Core Operations',['../d1/d78/tutorial_js_table_of_contents_core.html',1,'tutorial_js_root']]],
  ['camera_20calibration',['Camera Calibration',['../dc/dbb/tutorial_py_calibration.html',1,'tutorial_py_table_of_contents_calib3d']]],
  ['canny_20edge_20detection',['Canny Edge Detection',['../da/d22/tutorial_py_canny.html',1,'tutorial_py_table_of_contents_imgproc']]],
  ['changing_20colorspaces',['Changing Colorspaces',['../df/d9d/tutorial_py_colorspaces.html',1,'tutorial_py_table_of_contents_imgproc']]],
  ['contour_20features',['Contour Features',['../dd/d49/tutorial_py_contour_features.html',1,'tutorial_py_table_of_contents_contours']]],
  ['contour_20properties',['Contour Properties',['../d1/d32/tutorial_py_contour_properties.html',1,'tutorial_py_table_of_contents_contours']]],
  ['contours_20_3a_20getting_20started',['Contours : Getting Started',['../d4/d73/tutorial_py_contours_begin.html',1,'tutorial_py_table_of_contents_contours']]],
  ['contours_20hierarchy',['Contours Hierarchy',['../d9/d8b/tutorial_py_contours_hierarchy.html',1,'tutorial_py_table_of_contents_contours']]],
  ['contours_20_3a_20more_20functions',['Contours : More Functions',['../d5/d45/tutorial_py_contours_more_functions.html',1,'tutorial_py_table_of_contents_contours']]],
  ['camera_20calibration_20and_203d_20reconstruction',['Camera Calibration and 3D Reconstruction',['../d9/db7/tutorial_py_table_of_contents_calib3d.html',1,'tutorial_py_root']]],
  ['contours_20in_20opencv',['Contours in OpenCV',['../d3/d05/tutorial_py_table_of_contents_contours.html',1,'tutorial_py_table_of_contents_imgproc']]],
  ['core_20operations',['Core Operations',['../d7/d16/tutorial_py_table_of_contents_core.html',1,'tutorial_py_root']]],
  ['computational_20photography',['Computational Photography',['../d0/d07/tutorial_py_table_of_contents_photo.html',1,'tutorial_py_root']]],
  ['camera_20motion_20estimation',['Camera Motion Estimation',['../d5/dab/tutorial_sfm_trajectory_estimation.html',1,'tutorial_table_of_content_sfm']]],
  ['camera_20calibration_20and_203d_20reconstruction_20_28calib3d_20module_29',['Camera calibration and 3D reconstruction (calib3d module)',['../d6/d55/tutorial_table_of_content_calib3d.html',1,'tutorial_root']]],
  ['cnn_20for_203d_20object_20classification_20and_20pose_20estimation',['CNN for 3D Object Classification and Pose Estimation',['../d2/d42/tutorial_table_of_content_cnn_3dobj.html',1,'tutorial_contrib_root']]],
  ['computational_20photography_20_28photo_20module_29',['Computational photography (photo module)',['../da/de7/tutorial_table_of_content_photo.html',1,'tutorial_root']]],
  ['cascade_20classifier_20training',['Cascade Classifier Training',['../dc/d88/tutorial_traincascade.html',1,'tutorial_table_of_content_objdetect']]],
  ['creating_20a_20video_20with_20opencv',['Creating a video with OpenCV',['../d7/d9e/tutorial_video_write.html',1,'tutorial_table_of_content_videoio']]]
];
